// <auto-generated />
using System;
using Clavis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clavis.Migrations
{
    [DbContext(typeof(ClavisDbContext))]
    [Migration("20201209174052_clavis3")]
    partial class clavis3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Clavis.Models.Rezerwacje", b =>
                {
                    b.Property<int>("RezerwacjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rezerwacje_id")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("date_from");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime")
                        .HasColumnName("date_to");

                    b.Property<int?>("RoomsId")
                        .HasColumnType("int")
                        .HasColumnName("rooms_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int")
                        .HasColumnName("users_id");

                    b.HasKey("RezerwacjeId");

                    b.HasIndex("RoomsId");

                    b.HasIndex("UsersId");

                    b.ToTable("rezerwacje");
                });

            modelBuilder.Entity("Clavis.Models.Room", b =>
                {
                    b.Property<int>("RoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rooms_id")
                        .UseIdentityColumn();

                    b.Property<int?>("Miejsca")
                        .HasColumnType("int")
                        .HasColumnName("miejsca");

                    b.Property<string>("Numer")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numer");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("opis");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("uwagi");

                    b.HasKey("RoomsId")
                        .HasName("PK__rooms__80B6BBB3A1E37442");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Clavis.Models.Uprawnienium", b =>
                {
                    b.Property<int>("UprawnieniaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uprawnienia_id")
                        .UseIdentityColumn();

                    b.Property<int?>("RoomsId")
                        .HasColumnType("int")
                        .HasColumnName("rooms_id");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int")
                        .HasColumnName("users_id");

                    b.HasKey("UprawnieniaId")
                        .HasName("PK__uprawnie__5C4D723B347EB8D5");

                    b.HasIndex("RoomsId");

                    b.HasIndex("UsersId");

                    b.ToTable("uprawnienia");
                });

            modelBuilder.Entity("Clavis.Models.User", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("users_id")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Imie")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("imie");

                    b.Property<string>("Login")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("login");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nazwisko");

                    b.Property<byte[]>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("binary(64)")
                        .HasColumnName("password")
                        .IsFixedLength(true);

                    b.Property<string>("Uprawnienia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("uprawnienia");

                    b.HasKey("UsersId")
                        .HasName("PK__users__EAA7D14B5D9CBA18");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Clavis.Models.Rezerwacje", b =>
                {
                    b.HasOne("Clavis.Models.Room", "Rooms")
                        .WithMany("Rezerwacjes")
                        .HasForeignKey("RoomsId")
                        .HasConstraintName("FK_rezerwacje_rooms");

                    b.HasOne("Clavis.Models.User", "Users")
                        .WithMany("Rezerwacjes")
                        .HasForeignKey("UsersId")
                        .HasConstraintName("FK_rezerwacje_users");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Clavis.Models.Uprawnienium", b =>
                {
                    b.HasOne("Clavis.Models.Room", "Rooms")
                        .WithMany("Uprawnienia")
                        .HasForeignKey("RoomsId")
                        .HasConstraintName("FK_uprawnienia_rooms");

                    b.HasOne("Clavis.Models.User", "Users")
                        .WithMany("UprawnieniaNavigation")
                        .HasForeignKey("UsersId")
                        .HasConstraintName("FK_uprawnienia_users");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Clavis.Models.Room", b =>
                {
                    b.Navigation("Rezerwacjes");

                    b.Navigation("Uprawnienia");
                });

            modelBuilder.Entity("Clavis.Models.User", b =>
                {
                    b.Navigation("Rezerwacjes");

                    b.Navigation("UprawnieniaNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
